<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="base" params="length width height mass wheel_radius wheel_pos_z">
   <xacro:property name="yukseklik" value="0.085" />
   <xacro:property name="scale_ratio" value="0.0015" />

    <link name="base_footprint"/>
    
    <link name="base_link">
      <visual>
        <origin xyz="-0.3 0 ${yukseklik}" rpy="0 0 1.57"/>
        <geometry>
		<mesh scale="${scale_ratio} ${scale_ratio} ${scale_ratio}" filename="$(find robolaunch_cloudy_description)/urdf/meshes/arcelik/chassis_red.stl"/>
          <!-- <mesh ="" scale="0.001 0.001 0.001"/> -->
        </geometry>
        <material name="red">
          <color rgba="1.0 1.0 0.0 1.0" />
        </material>
      </visual>
      
      <collision>
        <origin xyz="0 0 ${yukseklik}" rpy="0 0 3.14"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${(1/12) * mass * ((width  * width)  + (height * height))}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * mass * ((length * length) + (height * height))}" iyz="0.0"
                 izz="${(1/12) * mass * ((length * length) + (width  * width))}"/>
      </inertial>
    </link>
    <link name="rplidar">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.1"  ixy="0"  ixz="0" iyy="0.1" iyz="0" izz="0.1" />
      </inertial>
  
      <visual>
        <origin xyz="0 0 ${yukseklik}" rpy="0 0 0" />
        <geometry>
		<mesh scale="${scale_ratio} ${scale_ratio} ${scale_ratio}" filename="$(find robolaunch_cloudy_description)/urdf/meshes/arcelik/lidar.stl"/>
        </geometry>
        <material name="yellow">
          <color rgba="0.1 0.6627 0.6627 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${yukseklik}" rpy="0 0 0"/>
        <geometry>
          <box size="0.1 0.1 0.1" />
        </geometry>
      </collision>
    </link>
        <link name="iskelet">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.1"  ixy="0"  ixz="0" iyy="0.1" iyz="0" izz="0.1" />
      </inertial>
  
      <visual>
        <origin xyz="0 0 ${yukseklik}" rpy="0 0 0" />
        <geometry>
          <mesh scale="${scale_ratio} ${scale_ratio} ${scale_ratio}" filename="$(find robolaunch_cloudy_description)/urdf/meshes/arcelik/son_rigs.stl"/>
        </geometry>
        <material name="yellow">
          <color rgba="0.1 0.6627 0.6627 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${yukseklik}" rpy="0 0 0"/>
        <geometry>
          <box size="0.1 0.1 0.1" />
        </geometry>
      </collision>
    </link>


    <link name="ust_plaka">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1"/>
        <inertia ixx="0.1"  ixy="0"  ixz="0" iyy="0.1" iyz="0" izz="0.1" />
      </inertial>
  
      <visual>
        <origin xyz="0 0 ${yukseklik}" rpy="0 0 0" />
        <geometry>
		<mesh scale="${scale_ratio} ${scale_ratio} ${scale_ratio}" filename="$(find robolaunch_cloudy_description)/urdf/meshes/arcelik/UstPlaka2.stl"/>
        </geometry>
        <material name="yellow">
          <color rgba="0.1 0.6627 0.6627 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${yukseklik}" rpy="0 0 0"/>
        <geometry>
          <box size="0.1 0.1 0.1" />
        </geometry>
      </collision>
    </link>
    
    <gazebo reference="base_link">  
      <visual>  
        <material>
          <ambient>0.8392 0.6314 0.0 1.0</ambient>  
          <diffuse>0.8392 0.6314 0.0 1.0</diffuse>  
          <specular>0.99 0.99 0.99 1.0</specular>  
          <emissive>0.0 0.0 0.0 0.0</emissive>  
        </material>
      </visual> 
    </gazebo>

    <joint name="base_to_footprint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin xyz="0 0 ${wheel_radius - wheel_pos_z}" rpy="0 0 0"/>
    </joint>
        <joint name="lidar_joint" type="fixed">
      <parent link="base_link"/>
      <child link="rplidar"/>
      <origin xyz="0.05 0.015 0.29" rpy="0 0 1.57"/>
    </joint>
        <joint name="rig_joint" type="fixed">
      <parent link="base_link"/>
      <child link="iskelet"/>
      <origin xyz="-0.235 0.18 0.09" rpy="0 0 -1.57"/>
    </joint>
        <joint name="ust_plaka_joint" type="fixed">
      <parent link="base_link"/>
      <child link="ust_plaka"/>
      <origin xyz="-0.3 0 0" rpy="0 0 1.57"/>
    </joint>

  </xacro:macro>
</robot>
