scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        max_x: 0.2
        max_y: 0.5
        max_z: 1.0
        min_x: -1.0
        min_y: -0.5
        min_z: -1.0
        
        invert: false # activate to remove all points outside of the box