
ekf_filter_node:
    ros__parameters:
        frequency: 50.0
        two_d_mode: true
        publish_tf: true
 
        map_frame: map             
        odom_frame: odom            
        base_link_frame: base_footprint
        world_frame: odom 

        #x     , y     , z,
        #roll  , pitch , yaw,
        #vx    , vy    , vz,
        #vroll , vpitch, vyaw,
        #ax    , ay    , az

        
        # odom0: /diffbot_base_controller/odom
        # odom0_config: [false, false, false,
        #                false, false, false,
        #                true, true, false,
        #                false, false, true,
        #                false, false, false]
        odom1: /odom_rf2o
        odom1_config: [false, false, false,
                       false, false, false,
                       true, true, false,
                       false, false, true,
                       false, false, false]

